### ISSUE TITLE
Having worship service and sunday school times and locations visible on home page

### ISSUE THREAD

**Issue by willervenscott** [oumc/oumc.github.io#21]
Place Sunday morning worship and Sunday School times on the home page in a highly visible location.  Include links to the worship service and Sunday school home pages.

**Comment by oxsdd** [comment]
This will be accomplished by always having an "upcoming event" for the Sunday services on the home page. For normal services, this will use the same "Join us for Worship" image used on the current www.oumc.org web page, or equivalent. For special services like the upcoming Ministry Sunday, a custom image may be used instead.
