### ISSUE TITLE
Update staff.html and positions.html

### ISSUE THREAD

**Issue by oumc** [oumc/oumc.github.io#8]
Are these pages correct?

**Comment by willervenscott** [comment]
The staff page was incorrect when I looked at it ten minutes ago.  We
currently are looking for an assistant youth leader and a Chancel Choir
Director, as far as postions go.

When we meet I would like a tutorial on how to submit suggestions for
corrections and changes.  I have compiled a list.  It is pretty small.  You
have done a great job!

See you at 1:00 p.m.
